apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    env: demo
spec:
  replicas: 2          
  selector:            
    matchLabels:      
      env: demo
  template:
    metadata:
      name: nginx-pod
      labels:
        env: demo
    spec:
      containers:
        - image: nginx
          name: nginx


# kubectl set image deploy/nginx-deploy nginx=nginx1.9.1
# dry run=> kubectl create deploy/nginx-new-deploy --image=nginx --dry-run=client -o yml > deploy.yml
