apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    env: demo
spec:
  replicas: 2          
  selector:            
    matchLabels:      
      env: demo
  template:
    metadata:
      name: nginx-pod
      labels:
        env: demo
    spec:
      containers:
        - image: nginx
          name: nginx
