apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp-pod
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo app is running && sleep 3600']
    env:
    - name: Fname
      value: "Vidit"
  initContainers:
  - name: init-service
    image: busybox:1.28
    command: ['sh' , '-c']
    args: ['until nslookup myservice.default.svc.cluster.local; do echo waiting for the service to be up and running; sleep 2; done']



    # kubectl create deploy nginx-deploy --image nginx --port 80
    # kubectl expose nginx-deploy --name myservice --port 80
