apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    env: demo
spec:
  replicas: 2          
  selector:            
    matchLabels:      
      env: demo
  template:
    metadata:
      name: nginx-pod
      labels:
        env: demo
    spec:
      containers:
        - image: nginx
          name: nginx


# some options to increase or decrease replicasets
# kubectl edit rs/nginx-rs    ---> edit config directly 
# kubectl scale --replicas=10 rs/nginx-rs  ---> spin ups 10 replicas on command
